CREATE TABLE tb_food_item (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) UNIQUE NOT NULL,
category ENUM('FRUITS', 'VEGETABLES', 'GRAINS', 'PROTEINS', 'DAIRY', 'SWEETS', 'SNACKS', 'CONDIMENTS', 'BEVERAGES', 'OTHERS') NOT NULL,
quantity INT NOT NULL,
expiration_date DATE NOT NULL
);